package cn.boc.sh.sfjh.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.8
 * Tue Aug 02 18:33:44 CST 2016
 * Generated source version: 2.2.8
 * 
 */
 
@WebService(targetNamespace = "http://ws.bocsh.com/", name = "BankService")
@XmlSeeAlso({ObjectFactory.class})
public interface BankService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getBIIFuncionTree", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.GetBIIFuncionTree")
    @WebMethod
    @ResponseWrapper(localName = "getBIIFuncionTreeResponse", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.GetBIIFuncionTreeResponse")
    public java.util.List<cn.boc.sh.sfjh.ws.BiiNode> getBIIFuncionTree(
        @WebParam(name = "locale", targetNamespace = "")
        java.lang.String locale,
        @WebParam(name = "tellerid", targetNamespace = "")
        java.lang.String tellerid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "querySubBranchList", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.QuerySubBranchList")
    @WebMethod
    @ResponseWrapper(localName = "querySubBranchListResponse", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.QuerySubBranchListResponse")
    public java.util.List<cn.boc.sh.sfjh.ws.TreeNode> querySubBranchList(
        @WebParam(name = "branchNo", targetNamespace = "")
        java.lang.String branchNo,
        @WebParam(name = "orgBankNo", targetNamespace = "")
        java.lang.String orgBankNo
    );

    @RequestWrapper(localName = "sendMail", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.SendMail")
    @WebMethod
    @ResponseWrapper(localName = "sendMailResponse", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.SendMailResponse")
    public void sendMail(
        @WebParam(name = "from", targetNamespace = "")
        java.lang.String from,
        @WebParam(name = "sendTo", targetNamespace = "")
        java.lang.String sendTo,
        @WebParam(name = "subject", targetNamespace = "")
        java.lang.String subject,
        @WebParam(name = "content", targetNamespace = "")
        java.lang.String content,
        @WebParam(name = "fileList", targetNamespace = "")
        java.util.List<java.lang.String> fileList
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "changeTellerPass", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.ChangeTellerPass")
    @WebMethod
    @ResponseWrapper(localName = "changeTellerPassResponse", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.ChangeTellerPassResponse")
    public java.lang.String changeTellerPass(
        @WebParam(name = "oldpassword", targetNamespace = "")
        java.lang.String oldpassword,
        @WebParam(name = "newpassword", targetNamespace = "")
        java.lang.String newpassword,
        @WebParam(name = "tellerid", targetNamespace = "")
        java.lang.String tellerid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getBranch", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.GetBranch")
    @WebMethod
    @ResponseWrapper(localName = "getBranchResponse", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.GetBranchResponse")
    public cn.boc.sh.sfjh.ws.Branch getBranch(
        @WebParam(name = "bankNo", targetNamespace = "")
        java.lang.String bankNo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPinyin", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.GetPinyin")
    @WebMethod
    @ResponseWrapper(localName = "getPinyinResponse", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.GetPinyinResponse")
    public java.lang.String getPinyin(
        @WebParam(name = "hanzi", targetNamespace = "")
        java.lang.String hanzi
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSubBranchList", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.GetSubBranchList")
    @WebMethod
    @ResponseWrapper(localName = "getSubBranchListResponse", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.GetSubBranchListResponse")
    public java.util.List<java.lang.String> getSubBranchList(
        @WebParam(name = "branchNo", targetNamespace = "")
        java.lang.String branchNo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendNotes", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.SendNotes")
    @WebMethod
    @ResponseWrapper(localName = "sendNotesResponse", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.SendNotesResponse")
    public java.lang.String sendNotes(
        @WebParam(name = "from", targetNamespace = "")
        java.lang.String from,
        @WebParam(name = "sendTo", targetNamespace = "")
        java.lang.String sendTo,
        @WebParam(name = "subject", targetNamespace = "")
        java.lang.String subject,
        @WebParam(name = "content", targetNamespace = "")
        java.lang.String content
    ) throws IOException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTellerFuncList", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.GetTellerFuncList")
    @WebMethod
    @ResponseWrapper(localName = "getTellerFuncListResponse", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.GetTellerFuncListResponse")
    public java.util.List<java.lang.String> getTellerFuncList(
        @WebParam(name = "tellerid", targetNamespace = "")
        java.lang.String tellerid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "isWorkingDate", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.IsWorkingDate")
    @WebMethod
    @ResponseWrapper(localName = "isWorkingDateResponse", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.IsWorkingDateResponse")
    public java.lang.String isWorkingDate(
        @WebParam(name = "date", targetNamespace = "")
        java.lang.String date
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "pivsCheck", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.PivsCheck")
    @WebMethod
    @ResponseWrapper(localName = "pivsCheckResponse", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.PivsCheckResponse")
    public java.lang.String pivsCheck(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    );

    @RequestWrapper(localName = "sendSms", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.SendSms")
    @WebMethod
    @ResponseWrapper(localName = "sendSmsResponse", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.SendSmsResponse")
    public void sendSms(
        @WebParam(name = "mobileno", targetNamespace = "")
        java.lang.String mobileno,
        @WebParam(name = "content", targetNamespace = "")
        java.lang.String content
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "validateUser", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.ValidateUser")
    @WebMethod
    @ResponseWrapper(localName = "validateUserResponse", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.ValidateUserResponse")
    public java.lang.String validateUser(
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFuncionTree", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.GetFuncionTree")
    @WebMethod
    @ResponseWrapper(localName = "getFuncionTreeResponse", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.GetFuncionTreeResponse")
    public java.util.List<cn.boc.sh.sfjh.ws.TreeNode> getFuncionTree(
        @WebParam(name = "locale", targetNamespace = "")
        java.lang.String locale,
        @WebParam(name = "tellerid", targetNamespace = "")
        java.lang.String tellerid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTeller", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.GetTeller")
    @WebMethod
    @ResponseWrapper(localName = "getTellerResponse", targetNamespace = "http://ws.bocsh.com/", className = "cn.boc.sh.sfjh.ws.GetTellerResponse")
    public cn.boc.sh.sfjh.ws.Teller getTeller(
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username
    );
}
