
package cn.boc.sh.sfjh.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.8
 * Tue Aug 02 18:33:44 CST 2016
 * Generated source version: 2.2.8
 * 
 */

@WebFault(name = "Exception", targetNamespace = "http://ws.bocsh.com/")
public class Exception_Exception extends java.lang.Exception {
    public static final long serialVersionUID = 20160802183344L;
    
    private cn.boc.sh.sfjh.ws.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, cn.boc.sh.sfjh.ws.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, cn.boc.sh.sfjh.ws.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public cn.boc.sh.sfjh.ws.Exception getFaultInfo() {
        return this.exception;
    }
}
