
package cn.boc.sh.sfjh.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.8
 * Tue Aug 02 18:33:44 CST 2016
 * Generated source version: 2.2.8
 * 
 */

@WebFault(name = "IOException", targetNamespace = "http://ws.bocsh.com/")
public class IOException_Exception extends java.lang.Exception {
    public static final long serialVersionUID = 20160802183344L;
    
    private cn.boc.sh.sfjh.ws.IOException ioException;

    public IOException_Exception() {
        super();
    }
    
    public IOException_Exception(String message) {
        super(message);
    }
    
    public IOException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public IOException_Exception(String message, cn.boc.sh.sfjh.ws.IOException ioException) {
        super(message);
        this.ioException = ioException;
    }

    public IOException_Exception(String message, cn.boc.sh.sfjh.ws.IOException ioException, Throwable cause) {
        super(message, cause);
        this.ioException = ioException;
    }

    public cn.boc.sh.sfjh.ws.IOException getFaultInfo() {
        return this.ioException;
    }
}
